name: build_and_deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      AZURE_SERVER_APP_NAME:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_ADMIN_PORTAL_DEPLOY_TOKEN:
        required: true
      AZURE_CLIENT_PORTAL_DEPLOY_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Build frontends
        run: |
          npm install
          cp frontend/apps/admin-portal/.env.${{ inputs.environment }} frontend/apps/admin-portal/.env
          rm frontend/apps/admin-portal/.env.*
          npm run build:frontends

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Admin Portal
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_ADMIN_PORTAL_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ./frontend/apps/admin-portal/dist

      - name: Create server bundle
        run: |
          npx turbo prune @repo/server
          cp -r ./backend/apps/server/migrations ./out/

      - name: Deploy Server
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.AZURE_SERVER_APP_NAME }}
          package: ./out

      # - name: Deploy Client Portal
      #   uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_CLIENT_PORTAL_DEPLOY_TOKEN }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     action: "upload"
      #     app_location: ./frontend/apps/client-portal/dist

      - name: Logout from Azure
        run: |
          az logout
